### ISSUE TITLE
[Suggestion] Add Ped checking to config

### ISSUE THREAD

**Issue by cm8263** [inferno-collection/Pass-Alarm#1]
**Is your feature request related to a problem? Please describe.**

Anyone can use the command.

**Describe the solution you would like**

Configurable Ped checking in the config.

**Describe alternatives you have considered**

Whitelisting the command: https://forum.fivem.net/t/how-to-whitelist-anything-in-a-resource-steamhex-and-ace-permissions/781946/

**Additional context**

N/A

**Comment by ResqDiver1317** [comment]
I personally would rather see a password on the command that can be set/changed as needed by the server staff. Requiring Hex/Ace means we have to update the list everytime we hire/fire personnel and tying to a PED model doesn't do any good for servers using EUP as almost everyone is using the same 2 base PEDs. I have the same opinion for the Fire Siren that is part of the Pager script, would rather the siren be done via a password than a whitelist.

**Comment by cm8263** [comment]
> I personally would rather see a password on the command that can be set/changed as needed by the server staff. Requiring Hex/Ace means we have to update the list everytime we hire/fire personnel and tying to a PED model doesn't do any good for servers using EUP as almost everyone is using the same 2 base PEDs. I have the same opinion for the Fire Siren that is part of the Pager script, would rather the siren be done via a password than a whitelist.

A password is a bit unorthodox, however, if that's what would suit you best, I can write a wiki page for you explaining how such a thing could be implemented. I'll link it here once it's written.

**Comment by cm8263** [comment]
Added in https://github.com/inferno-collection/Pass-Alarm/commit/7ded8f2db88bbd40df2198f94e1f276f477d1f6a.
