### ISSUE TITLE
[Suggestion] Add Panic Button

### ISSUE THREAD

**Issue by cm8263** [inferno-collection/Pass-Alarm#2]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you would like**

Added panic button so players don't have to wait 18 seconds.

**Describe alternatives you have considered**

N/A

**Additional context**

N/A

**Comment by ResqDiver1317** [comment]
just be sure this isn't done with a command of /panic. "/pass panic" would be fine, but I've seen several CADs that use /panic in their CAD/FiveM integration

**Comment by cm8263** [comment]
> just be sure this isn't done with a command of /panic. "/pass panic" would be fine, but I've seen several CADs that use /panic in their CAD/FiveM integration

Yes we saw this one coming a mile away haha. Currently, it is planned to be `passpanic` 👌

**Comment by cm8263** [comment]
Added in https://github.com/inferno-collection/Pass-Alarm/commit/7ded8f2db88bbd40df2198f94e1f276f477d1f6a.
