### ISSUE TITLE
[Suggestion] Stage 2 should not be turned off with movement

### ISSUE THREAD

**Issue by cm8263** [inferno-collection/Pass-Alarm#4]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you would like**

Stage 2 should be turned off via a key or a command, not movement, as this is not accurate to real life.

**Describe alternatives you have considered**

N/A

**Additional context**

N/A

**Comment by ResqDiver1317** [comment]
I agree with this. Stage 2, which typically means an FF down, must be muted with a button press or by turning off the device.  Partner or RIT grabbing the downed FF and dragging them out does not stop the alarm, they have to manually stop the alarm. The only downside of doing this script that way is how would the partner/RIT do this on someone else's device? It would have to be RP'd that they did it and the downed FF would have to do the command themselves but if they were "dead" from the fire they often cannot see the /me texts unless done globally in chat. 

My suggestion would be to just leave this as it is, but require the movement to be at least a few feet vs a few inches to disable stage 2, or have a command that ties back to the person down such as /mutepass ID# (if the downed FF is played ID 407, "/mutepass 407") that way the person pulling them out can actually silence the device on someone else

**Comment by cm8263** [comment]
> I agree with this. Stage 2, which typically means an FF down, must be muted with a button press or by turning off the device. Partner or RIT grabbing the downed FF and dragging them out does not stop the alarm, they have to manually stop the alarm. The only downside of doing this script that way is how would the partner/RIT do this on someone else's device? It would have to be RP'd that they did it and the downed FF would have to do the command themselves but if they were "dead" from the fire they often cannot see the /me texts unless done globally in chat.
> 
> My suggestion would be to just leave this as it is, but require the movement to be at least a few feet vs a few inches to disable stage 2, or have a command that ties back to the person down such as /mutepass ID# (if the downed FF is played ID 407, "/mutepass 407") that way the person pulling them out can actually silence the device on someone else

While I understand exactly what you're saying, I think we will stick with the current plan, which is that the 'downed' FF is the only one who can do the command; they can, through RP, have their alarm turned off by another person 👍

**Comment by cm8263** [comment]
Added in https://github.com/inferno-collection/Pass-Alarm/commit/7ded8f2db88bbd40df2198f94e1f276f477d1f6a.
